events {}

http {
  server {
    listen 80;

    # Frontend
    location / {
      proxy_pass http://frontend:3000;
    }

    # Backend API
  
    location /api/ {
  rewrite ^/api/(.*)$ /$1 break;
  proxy_pass http://backend:8000;
}
    # Improve performance
    gzip on;
    gzip_types text/plain application/json;

    # WebSocket support (future safe)
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
  }
}